[[pages]]
name = "home"  # Text displayed in desktop version of navbar header
align = "left"  # within left and right-aligned, the definition order in this document determines the order
icon = "img/icons/home.svg"  # relative path to icon that's displayed for the mobile version
url = "results.html"  # (relative) link to the page it should link to. External links will have a little icon showing it's an out-link.
icon_only = true  # If set, never show the text of `name` but show the icon even in desktop mode (default: false).

[[pages]]
name = "results"
align = "right"
# icon = ""
url = "results.html"

[[pages]]
name = "frameworks"
align = "right"
# icon = ""
url = "frameworks.html"

[[pages]]
name = "papers"
align = "right"
# icon = ""
url = "papers.html"

[[pages]]
name = "user guide"
align = "right"
# icon = ""
url = "user_guide.html"

[[pages]]
name = "contributing"
align = "right"
# icon = ""
url = "contributing.html"

[[pages]]
name = "discussion"
align = "right"
# icon = ""
url = "https://github.com/openml/automlbenchmark/discussions/216"

[[pages]]
name = "Github"
align = "right"
icon = "img/logos/GitHub-Mark-Light-64px.png"
url = "https://github.com/openml/automlbenchmark/"
icon_only = true