name: Run All Modes

on:
  - pull_request
  - workflow_dispatch


jobs:

  baseline:
    name: ${{ matrix.framework }}/${{ matrix.mode}}/${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [constantpredictor, randomforest, autogluon]
        task: [iris, kc2, cholesterol]
        mode: [local, docker]
      fail-fast:  false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Create venv
        run: python -m venv venv
      - uses: actions/cache@v3
        id: cache
        with:
          path: /home/runner/work/automlbenchmark/automlbenchmark/venv/lib/python3.9/site-packages
          key: pip-v3-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-v3-
      - name: Install Requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip show openml
      - name: Run ${{ matrix.framework }}
        run: |
          source venv/bin/activate
          yes | python runbenchmark.py ${{ matrix.framework }} -t ${{ matrix.task }} -m ${{ matrix.mode}} -f 0 -e -s force