# This workflow periodically runs the automl benchmark for the supported frameworks to report
# any errors that may arise from updates versions.
# It can also be invoked manually to call `runbenchmark` for a single framework.
name: Run `runbenchmark.py`

on:
  schedule:
    - cron: '0/5 * * * *'

  workflow_dispatch:
    inputs:
      python_version:
        default: '3.9'
      os:
        default: 'ubuntu-latest'
      framework:
        default: 'randomforest'
      options:
        default: ''

jobs:
  set_os:
    # The matrix of the next job includes an extra job that is defined by the workflow dispatch input
    # However, on a scheduled job, this input is an empty string. Which means that it can not be
    # directly used in the `runs-on` field. So we set up a variable to use for `runs-on` that
    # is always populated
    runs-on: 'ubuntu-latest'
    outputs:
      os: ${{ steps.os.outputs.os }}
    steps:
      - id: os
        run: |
          echo "os=${{ inputs.os }}" >> "$GITHUB_OUTPUT"
          if [[ -z "${{ inputs.os }}" ]]; then
            echo "os=ubuntu-latest" >> "$GITHUB_OUTPUT"
          fi
      - name: Echo Inputs # Just for debugging purposes
        run: echo "${{ toJSON(github.event.inputs) }}"

  run_benchmark:
    needs: [set_os]
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.9']
        framework: ['autogluon', 'autosklearn', 'flaml', 'gama', 'h2oautoml','lama', 'naml', 'randomforest', 'tpot']
        include:
          - python: ${{ inputs.python_version }}
            os: ${{ needs.set_os.outputs.os }}
            framework: ${{ inputs.framework }}
            options: ${{ inputs.options }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Stop Matrix Jobs on Dispatch
        if: (inputs.python_version != '') && !(( matrix.framework == inputs.framework ) && ( matrix.os == inputs.os )&& ( matrix.python == inputs.python_version ))
        # (The job is started by a workflow dispatch) && !(this is the matrix job that represents the workflow trigger)
        run: |
          exit 1
      - name: Runs on ${{ matrix.os }}
        run: echo Preparing to benchmark ${{ matrix.framework }} ${{ matrix.options }}
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install Py${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install benchmark dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install ${{ matrix.framework }}
        run: python runbenchmark.py ${{ matrix.framework }} -s only
        env:
          GITHUB_PAT: ${{ secrets.PUBLIC_ACCESS_GITHUB_PAT }}
      - name: Benchmark ${{ matrix.framework }}
        run: python runbenchmark.py ${{ matrix.framework }} ${{ matrix.options }}
