# This workflow periodically runs the automl benchmark for the supported frameworks to report
# any errors that may arise from updates versions.
# It can also be invoked manually to call `runbenchmark` for a single framework.
name: Run `runbenchmark.py`

permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: '0/5 * * * *'

  workflow_dispatch:
    inputs:
      python_version:
        default: '3.9'
      os:
        default: 'ubuntu-latest'
      framework:
        default: 'randomforest'
      options:
        default: ''

jobs:
  set_os:
    # The matrix of the next job includes an extra job that is defined by the workflow dispatch input
    # However, on a scheduled job, this input is an empty string. Which means that it can not be
    # directly used in the `runs-on` field. So we set up a variable to use for `runs-on` that
    # is always populated
    runs-on: 'ubuntu-latest'
    outputs:
      os: ${{ steps.os.outputs.os }}
    steps:
      - id: os
        run: |
          echo "os=${{ inputs.os }}" >> "$GITHUB_OUTPUT"
          if [[ -z "${{ inputs.os }}" ]]; then
            echo "os=ubuntu-latest" >> "$GITHUB_OUTPUT"
          fi
      - name: Echo Inputs # Just for debugging purposes
        run: echo "${{ toJSON(github.event.inputs) }}"

  run_benchmark:
    needs: [set_os]
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.9']
        framework: ['autogluon', 'autosklearn', 'flaml', 'gama', 'h2oautoml','lightautoml', 'naiveautoml', 'randomforest', 'tpot']
        include:
          - python: ${{ inputs.python_version }}
            os: ${{ needs.set_os.outputs.os }}
            framework: ${{ inputs.framework }}
            options: ${{ inputs.options }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Stop Matrix Jobs on Dispatch
        if: (inputs.python_version != '') && !(( matrix.framework == inputs.framework ) && ( matrix.os == inputs.os )&& ( matrix.python == inputs.python_version ))
        # (The job is started by a workflow dispatch) && !(this is the matrix job that represents the workflow trigger)
        run: |
          exit 1
      - name: Runs on ${{ matrix.os }}
        run: |
          echo Preparing to benchmark ${{ matrix.framework }} ${{ matrix.options }}
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install Py${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install benchmark dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install ${{ matrix.framework }}
        id: install
        run: python runbenchmark.py ${{ matrix.framework }} -s only
        env:
          GITHUB_PAT: ${{ secrets.PUBLIC_ACCESS_GITHUB_PAT }}
      - name: Report Installation Failure
        if: failure() && steps.install.conclusion == 'failure'
        run: |  # https://github.com/orgs/community/discussions/8945 can't link to job in matrix...
          LOG_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/"
          TITLE="${{ matrix.framework }} failed to install"
          NUMBERS=$(gh issue list --json number,title,closed --jq '.[] | select( .title == "'"$TITLE"'") | select( .closed == false ) | {number: .number}')
          echo "Found " $(echo "$NUMBERS" | wc -l) " issues: $NUMBERS"
          NUMBER=$(echo "$NUMBERS" | sed -E 's/[^0-9]//g' | head -n1)
          if [[ -z "$NUMBER" ]]; then  
            gh issue create --title "$TITLE" --label "bot" --body "$LOG_URL"
          else
            gh issue comment "$NUMBER" --body "issues persist: $LOG_URL"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Benchmark ${{ matrix.framework }}
        id: run
        run: python runbenchmark.py ${{ matrix.framework }} ${{ matrix.options }} -f 0
      - name: Report Running Failure
        if: failure() && steps.run.conclusion == 'failure'
        run: |
          LOG_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/"
          gh issue create --title "${{ matrix.framework }} fails on test" --label "bot" --body "$LOG_URL"
        env:
          GH_TOKEN: ${{ github.token }}
